# Generated by Django 2.1.15 on 2024-11-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('birthday', 'Birthday Party'), ('corporate', 'Corporate Event')], max_length=20, null=True),
        ),
    ]
