# Generated by Django 2.1.15 on 2024-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20241107_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor_type', models.CharField(choices=[('caterer', 'Caterer'), (
                    'photographer', 'Photographer'), ('decorator', 'Decorator')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='events.Vendor'),
        ),
    ]
