# Generated by Django 4.2.16 on 2024-11-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
